
export const REMOVE_ARTICLE = 9;
export const POST_ARTICLE = 10;
export const UPDATE_ARTICLE = 11;
export const UPDATE_POST_DATA = 12;
export const CHANGE_POST_CATAGORY = 13;
export const CHANGE_POST_TAGS = 14;

export default {POST_ARTICLE,UPDATE_ARTICLE,CHANGE_POST_TAGS,CHANGE_POST_CATAGORY,UPDATE_POST_DATA}